version: '3'

services:
  charlotte:
    build: .
    container_name: charlotte-bot
    restart: unless-stopped
    shm_size: '2gb'
    command: supervisord -c /app/supervisord.conf
    ports:
      - "5000:5000"  # 로그 서버 포트
    volumes:
      - type: bind
        source: /home/mizore/charlotte/
        target: /app  
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - BLOCKED_USER_IDS=${BLOCKED_USER_IDS}