version: '3'

services:
  charlotte:
    build: .
    container_name: charlotte-bot
    restart: unless-stopped
    command: python charlotte_bot.py
    volumes:
      - ./:/app
      - ./.env:/app/.env
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - BLOCKED_USER_IDS=${BLOCKED_USER_IDS}