"""Operational defaults that are intentionally not public configuration."""

ATTACHMENT_READ_TIMEOUT = 30.0
OWNER_DM_TIMEOUT = 5.0
PROVIDER_OPERATION_TIMEOUT = 45.0
PROVIDER_MAX_CONCURRENCY = 8
VOICE_OPERATION_TIMEOUT = 30.0
YTDLP_SOCKET_TIMEOUT = 15

# Docker grants the process 30 seconds before SIGKILL. Keep the sum of the
# application-level shutdown stages below that externally enforced deadline.
SHUTDOWN_AUXILIARY_TIMEOUT = 1.0
SHUTDOWN_PLAYERS_TIMEOUT = 20.0
SHUTDOWN_DISCORD_TIMEOUT = 5.0
SHUTDOWN_VOICE_TIMEOUT = 5.0
SHUTDOWN_DETACHED_CLEANUP_TIMEOUT = 5.0

VOICE_RECONNECT_ATTEMPTS = 3
VOICE_RECONNECT_WINDOW = 15.0
ERROR_SUPPRESSION_WINDOW = 300.0
HEALTH_MAX_AGE = 60.0
