name: Deploy to server.kiba.red

on:
  push:
    tags:
      - 'v*.*.*'
      # 모든 태그에 대해 동작하려면 - '*' 로 작성 가능

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Deploy Bot
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}       # server.kiba.red
          username: ${{ secrets.SERVER_USER }}   # SSH 접속 사용자
          password: ${{ secrets.SERVER_SSH_KEY }}     # SSH 개인 키
          port: 22                               # 기본: 22
          script: |
            # 배포 디렉토리 이동
            cd /home/mizore/charlotte

            # 필요하다면 로컬에서 이미 clone 되어있는 레포를 pull
            git pull

            echo "${{ secrets.SERVER_SSH_KEY }}" | sudo -S docker compose down
            # 캐싱을 위해 최신화 비활성화
            # echo "${{ secrets.SERVER_SSH_KEY }}" | sudo -S docker compose build --pull
            echo "${{ secrets.SERVER_SSH_KEY }}" | sudo -S docker compose up -d
            # 캐싱을 위해 이전 이미지 제거 비활성화
            # echo "${{ secrets.SERVER_SSH_KEY }}" | sudo -S docker image prune -af
